FROM node:erbium-stretch-slim as build

WORKDIR /build

COPY package.json .
COPY yarn.lock .
COPY packages/core ./packages/core
COPY packages/be-config ./packages/be-config

RUN yarn install --frozen-lockfile

WORKDIR /build/packages/be-config
RUN yarn build

########################################################################################################################

FROM node:erbium-stretch-slim

LABEL name="mia-microlc-config-manager" \
      description="The Mia-Platform micro fontend solution configuration manager" \
      eu.mia-platform.url="https://www.mia-platform.eu" \
      eu.mia-platform.version="0.1.0"

ENV LOG_LEVEL=info
ENV SERVICE_PREFIX=/
ENV HTTP_PORT=3000
ENV NODE_ENV=production

WORKDIR /home/node/app

COPY package.json .
COPY yarn.lock .

COPY --from=build /build/packages/core/package.json /home/node/app/packages/core/package.json
COPY --from=build /build/packages/core/dist /home/node/app/packages/core/dist

COPY --from=build /build/packages/be-config/package.json /home/node/app/packages/be-config/package.json
COPY --from=build /build/packages/be-config/dist /home/node/app/packages/be-config/dist

RUN yarn install --frozen-lockfile --ignore-scripts

USER node

CMD yarn be-config start --options --port "$HTTP_PORT" --log-level "$LOG_LEVEL" --prefix="$SERVICE_PREFIX" --address 0.0.0.0
