export const baseUrl = process.env['BASE_URL'] || 'http://localhost:3000'
export const logoSelector = '[data-testid=company-logo]'
export const burgerSelector = '[data-testid=top-bar-side-menu-toggle]'
export const logoUrl = 'https://media-exp1.licdn.com/dms/image/C4D0BAQEf8hJ29mN6Gg/company-logo_200_200/0/1615282397253?e=2159024400&v=beta&t=tQixwAMJ5po8IkukxMyFfeCs-t-zZjyPgDfdy12opvI'
export const userMenuSelector = '[data-testid=userMenu_container]'
