/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn make-types` to regenerate this file.
 */

/**
 * Prefix to apply to the generated sed of variables. If more thant one is specified, a set for each prefix will be generated.
 */
export type VarsPrefix = string | string[]
/**
 * Color definition. It can be a Hex, 8-digit Hex, RGB, RGBA HSL, HSLA, HSV, HSVA, CSS color name string
 */
export type Color = string
/**
 * Color definition. It can be a Hex, 8-digit Hex, RGB, RGBA HSL, HSLA, HSV, HSVA, CSS color name string
 */
export type Color1 = string
/**
 * Color definition. It can be a Hex, 8-digit Hex, RGB, RGBA HSL, HSLA, HSV, HSVA, CSS color name string
 */
export type Color2 = string
/**
 * Color definition. It can be a Hex, 8-digit Hex, RGB, RGBA HSL, HSLA, HSV, HSVA, CSS color name string
 */
export type Color3 = string
/**
 * Color definition. It can be a Hex, 8-digit Hex, RGB, RGBA HSL, HSLA, HSV, HSVA, CSS color name string
 */
export type Color4 = string
/**
 * Color definition. It can be a Hex, 8-digit Hex, RGB, RGBA HSL, HSLA, HSV, HSVA, CSS color name string
 */
export type Color5 = string

/**
 * Micro-lc theme manager for Ant Design
 */
export interface Config {
  $schema?: string
  "vars-prefix"?: VarsPrefix
  "primary-color"?: Color
  "info-color"?: Color1
  "success-color"?: Color2
  "processing-color"?: Color3
  "error-color"?: Color4
  "warning-color"?: Color5
}
