/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn make-types` to regenerate this file.
 */

export interface Translations {
  $schema?: string
  "MLC-LAYOUT"?: {
    collapse?: string
    light?: string
    dark?: string
    logout?: string
  }
}
