// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  'add-ons': [
    {
      dirName: 'add-ons',
      type: 'autogenerated',
    },
  ],
  api: [
    {
      dirName: 'api',
      type: 'autogenerated',
    },
  ],
  docs: [
    {
      dirName: 'docs',
      type: 'autogenerated',
    },
  ],
}

module.exports = sidebars
