/* eslint-disable sort-keys-fix/sort-keys-fix */

/*
 * WARINNG!
 * Docusaurus elects the first document of the first sidebar it finds as link for the version in the dropdown.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      dirName: 'docs',
      type: 'autogenerated',
    },
  ],
  api: [
    {
      dirName: 'api',
      type: 'autogenerated',
    },
  ],
  'add-ons': [
    {
      dirName: 'add-ons',
      type: 'autogenerated',
    },
  ],
}

module.exports = sidebars
